
package com.palmble.qd_manager.xhpos;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "StandardPolicy", targetNamespace = "xhpos", wsdlLocation = "http://123.127.246.22:8080/pos/services/StandardPolicy?wsdl")
public class StandardPolicy
    extends Service
{

    private final static URL STANDARDPOLICY_WSDL_LOCATION;
    private final static WebServiceException STANDARDPOLICY_EXCEPTION;
    private final static QName STANDARDPOLICY_QNAME = new QName("xhpos", "StandardPolicy");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://123.127.246.22:8080/pos/services/StandardPolicy?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        STANDARDPOLICY_WSDL_LOCATION = url;
        STANDARDPOLICY_EXCEPTION = e;
    }

    public StandardPolicy() {
        super(__getWsdlLocation(), STANDARDPOLICY_QNAME);
    }

    public StandardPolicy(WebServiceFeature... features) {
        super(__getWsdlLocation(), STANDARDPOLICY_QNAME, features);
    }

    public StandardPolicy(URL wsdlLocation) {
        super(wsdlLocation, STANDARDPOLICY_QNAME);
    }

    public StandardPolicy(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, STANDARDPOLICY_QNAME, features);
    }

    public StandardPolicy(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StandardPolicy(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns StandardPolicyPortType
     */
    @WebEndpoint(name = "StandardPolicyHttpPort")
    public StandardPolicyPortType getStandardPolicyHttpPort() {
        return super.getPort(new QName("xhpos", "StandardPolicyHttpPort"), StandardPolicyPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StandardPolicyPortType
     */
    @WebEndpoint(name = "StandardPolicyHttpPort")
    public StandardPolicyPortType getStandardPolicyHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("xhpos", "StandardPolicyHttpPort"), StandardPolicyPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (STANDARDPOLICY_EXCEPTION!= null) {
            throw STANDARDPOLICY_EXCEPTION;
        }
        return STANDARDPOLICY_WSDL_LOCATION;
    }

}
